{
 "title": "New dashboard",
 "time": { "from": "2021-02-01T00:00:00.000Z", "to": "2021-02-10T00:00:00.000Z" },
 "panels": [
  {
   "title": "share_missing_values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,share_missing_values FROM dummy_metrics "
    }
   ]
  },
  {
   "title": "prediction_drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, prediction_drift FROM dummy_metrics"
    }
   ]
  },
  {
   "title": "num_drifted_columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT timestamp,num_drifted_columns FROM dummy_metrics "
    }
   ]
  }
 ]
}